monolog:
    handlers:
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.php.log"
            formatter: 'Nalogka\Monolog\Formatter\MultilineFormatter'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            bubble: false
            channels: ["php"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            formatter: 'Nalogka\Monolog\Formatter\MultilineFormatter'
            level: info
            bubble: false
            channels: ["app"]
        error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            formatter: 'Nalogka\Monolog\Formatter\MultilineFormatter'
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
