monolog:
    handlers:
        deprecation:
            type: 'null'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            bubble: false
            channels: ["php"]
        main:
            type: stream
            path: "php://stderr"
            formatter: 'Nalogka\Monolog\Formatter\MultilineFormatter'
            level: info
            bubble: false
            channels: ["app"]
        error:
            type: fingers_crossed
            action_level: error
            handler: error_nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        error_nested:
            type: stream
            path: "php://stderr"
            formatter: 'Nalogka\Monolog\Formatter\MultilineFormatter'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
